# This is to evaluate the final response generated by reponse agent
import os

from back.utils.groq.groq_provider import GroqProvider
from back.state import SupportState
from utils.prompts.response_evaluator_prompt import ResponseEvaluatorPrompt

class ResponseEvaluatorAgent:
    def __init__(self):
        self.MODEL_NAME = os.environ.get("RESPONSE_AGENT_RESPONSE_EVALUATOR_MODEL_NAME")
        self.RESPONDER_RESPONSE_EVALUATOR_LLM = GroqProvider(self.MODEL_NAME)
        
    def evaluator(self, state: SupportState):
        review_prompt = ResponseEvaluatorPrompt.prompt_dumper(state)
        
        try: 
            review_response = self.RESPONDER_RESPONSE_EVALUATOR_LLM.generate_response(review_prompt)
            
            review_response_text = review_response.text
            
            return review_response_text
        
        except Exception as e:
            return str(e)
